apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudmapper-pvc
  namespace: texera
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
